baseURL: "https://username.github.io"  # NANTI DIGANTI
languageCode: "id-id"
title: "edmod"
theme: "PaperMod"

params:
  author: "Edward Domakubun"
  description: "Blog pribadi saya"
  
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 10
    - name: "Posts"
      url: "/posts/"
      weight: 20
    - name: "About"
      url: "/about/"
      weight: 30